MA-19153 Fix emulator build error
Fix the emulator build error like below:
  error: system/core/trusty/apploader/Android.bp:17:1: module "trusty_apploader" variant "android_vendor.30_x86_64": depends on
  disabled module "libfsldisplay"

Test: emulator build.

Change-Id: I63f75766f1592c07511bf36a79c656c33f0e91b7
Signed-off-by: Ji Luo <ji.luo@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/16096
Reviewed-by: Jindong Yue <jindong.yue@nxp.com>
(cherry picked from commit ef63949caf629074141b49f42a233f70fa47895b)
Reviewed-on: http://androidsource.ap.freescale.net/project/16109